### ISSUE TITLE
User of new_sec_key might assume it fills the entire buffer

### ISSUE THREAD

**Issue by defuse** [KizzyCode/crypto_api_chachapoly#3]
I can imagine someone misinterpreting `new_sec_key`'s thinking that it fills the *entire* buffer with random bytes, but it actually only fills the first 32-bytes. To avoid accidental mistakes, I'd recommend changing [this line](https://github.com/KizzyCode/crypto_api_chachapoly/blob/e62aeefadb489dace35961ed6fd69b80ed410750/src/chachapoly_ietf.rs#L78) to `buf.len() == 32` instead of `buf.len() < 32`.

(BTW I compared the ChaCha20 and Poly1305 implementations to [RFC 8439](https://tools.ietf.org/html/rfc8439). I didn't look at the tests. This issue and #2 are the only problems I found).

**Comment by KizzyCode** [comment]
That's a good point – I previously decided against a strong check like this, but I didn't have that risk in mind. I'm currently checking if I should rework the code to use [len_constraints](https://crates.io/crates/len_constraints) in all non-trait APIs and during this I'll change that too.

**Comment by KizzyCode** [comment]
Fixed in https://github.com/KizzyCode/crypto_api_chachapoly/commit/0aaded900723ad8741fdc41ccffbae1f37fa55e2 and https://github.com/KizzyCode/crypto_api_chachapoly/commit/8e58348dcafdc56918c1785688466a010d3987a9 and https://github.com/KizzyCode/crypto_api_chachapoly/commit/952b5951940ff5d98b89e00540b1c496934fb004
